### ISSUE TITLE
Variable "settings" does not exist.

### ISSUE THREAD

**Issue by KevinBeckers** [studioespresso/craft-unsplash#1]
Twig_Error_Runtime: Variable "settings" does not exist. in /home/vagrant/code/bze/vendor/studioespresso/craft-splashingimages/src/templates/_search.twig:26
Stack trace:
#0 /home/vagrant/code/bze/storage/runtime/compiled_templates/dc/dcb79ac2455f82fa858affe5a0a5043f50a93bba6e6283d81afd0492586a9f4b.php(35): __TwigTemplate_4f7bc28072ac6feab14b1d780db54cdcd3dbcba71759bb3915b02d147dd34d72->{closure}()
#1 /home/vagrant/code/bze/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_4f7bc28072ac6feab14b1d780db54cdcd3dbcba71759bb3915b02d147dd34d72->doDisplay(Array, Array)
#2 /home/vagrant/code/bze/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /home/vagrant/code/bze/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#4 /home/vagrant/code/bze/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#5 /home/vagrant/code/bze/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#6 /home/vagrant/code/bze/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#7 /home/vagrant/code/bze/vendor/craftcms/cms/src/web/View.php(308): Twig_Environment->render('splashing-image...', Array)
#8 /home/vagrant/code/bze/vendor/craftcms/cms/src/web/View.php(356): craft\web\View->renderTemplate('splashing-image...', Array)
#9 /home/vagrant/code/bze/vendor/craftcms/cms/src/web/Controller.php(121): craft\web\View->renderPageTemplate('splashing-image...', Array)
#10 /home/vagrant/code/bze/vendor/studioespresso/craft-splashingimages/src/controllers/ImagesController.php(70): craft\web\Controller->renderTemplate('splashing-image...', Array)
#11 [internal function]: studioespresso\splashingimages\controllers\ImagesController->actionSearch()
#12 /home/vagrant/code/bze/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /home/vagrant/code/bze/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /home/vagrant/code/bze/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('search', Array)
#15 /home/vagrant/code/bze/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('search', Array)
#16 /home/vagrant/code/bze/vendor/craftcms/cms/src/web/Application.php(251): yii\base\Module->runAction('splashing-image...', Array)
#17 /home/vagrant/code/bze/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('splashing-image...', Array)
#18 /home/vagrant/code/bze/vendor/craftcms/cms/src/web/Application.php(216): yii\web\Application->handleRequest(Object(craft\web\Request))
#19 /home/vagrant/code/bze/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /home/vagrant/code/bze/public/index.php(22): yii\base\Application->run()
#21 {main}

### Steps to reproduce

1. Search for "cat"

### Additional info

PHP version | 7.2.0
MySQL 5.7.20
GD 7.2.0
Craft Pro 3.0.0-RC7
2.0.13.1
2.4.4
6.2.1
0.7-dev
Splashing Images 1.0.0

**Comment by KevinBeckers** [comment]
Fixed in fork. I will add a pull request soon.
#2
